### ISSUE TITLE
Gather user feedback

### ISSUE THREAD

**Issue by Malaguth** [Malaguth/skill-tracking#10]
# Description

If possible, gather feedback from potential users about what they want in a product. This could be done through surveys, interviews, or focus groups. User feedback can provide valuable insights into user needs and preferences.

## Acceptance Criteria

Meet with possible users and interview them about the project to gather information about features they want and why they would use the software.

**Comment by ViniciusLAAraujo** [comment]
Following pt-BR questions suggestion I've made . Was thinking about sending it via google forms.

[PerguntasSkill-track.txt](https://github.com/Malaguth/skill-tracking/files/13836127/PerguntasSkill-track.txt)

**Comment by ViniciusLAAraujo** [comment]
[PerguntasSkill-track.txt](https://github.com/Malaguth/skill-tracking/files/14056888/PerguntasSkill-track.txt)

**Comment by ViniciusLAAraujo** [comment]
[AnswersFeedbackGathering.txt](https://github.com/Malaguth/skill-tracking/files/14056977/AnswersFeedbackGathering.txt)
@Malaguth  Some answers I got, even though the the extension it's .txt I  formatted it as a markdown if we decide to incorporate it on documentation

**Comment by Malaguth** [comment]
@ViniciusLAAraujo I downloaded the file and deleted the comment because it contains sensitive information about a person. The current repository is public, so I decide to remove the comment to preserve the person/company and I'll use the no sensitive information on the project on next refinements.
